/// MARK: - Unit Test Skill
/// Generates unit tests for changed files, checks test coverage,
/// and runs the test suite immediately after generation.
/// Framework auto-detected from package.json (Jest default).

const { execFile, spawn } = require('child_process');
const { promisify } = require('util');
const fs = require('fs');
const path = require('path');
const BaseSkill = require('./Core/BaseSkill');

const execFileAsync = promisify(execFile);

// ── Test framework detection ──────────────────────────────────────────────

function detectTestFramework(repoPath) {
  try {
    const pkgPath = path.join(repoPath, 'package.json');
    if (!fs.existsSync(pkgPath)) return { name: 'jest', runner: 'npx jest', coverage: 'npx jest --coverage' };
    const pkg = JSON.parse(fs.readFileSync(pkgPath, 'utf8'));
    const allDeps = { ...pkg.dependencies, ...pkg.devDependencies };

    if (allDeps['vitest'])      return { name: 'vitest',  runner: 'npx vitest run', coverage: 'npx vitest run --coverage' };
    if (allDeps['mocha'])       return { name: 'mocha',   runner: 'npx mocha',      coverage: 'npx nyc mocha' };
    if (allDeps['jasmine'])     return { name: 'jasmine', runner: 'npx jasmine',     coverage: 'npx nyc jasmine' };
    // Default: Jest (standard for RN)
    return { name: 'jest', runner: 'npx jest', coverage: 'npx jest --coverage --coverageReporters=text' };
  } catch (_) {
    return { name: 'jest', runner: 'npx jest', coverage: 'npx jest --coverage --coverageReporters=text' };
  }
}

// ── Test file location detection ──────────────────────────────────────────

function findTestFile(sourceFile, repoPath) {
  const ext = path.extname(sourceFile);
  const base = path.basename(sourceFile, ext);
  const dir = path.dirname(sourceFile);

  const candidates = [
    // Co-located: LoginScreen.test.tsx
    path.join(repoPath, dir, `${base}.test${ext}`),
    path.join(repoPath, dir, `${base}.spec${ext}`),
    // __tests__ sibling folder
    path.join(repoPath, dir, '__tests__', `${base}.test${ext}`),
    path.join(repoPath, dir, '__tests__', `${base}.spec${ext}`),
    // Root __tests__ mirroring src structure
    path.join(repoPath, '__tests__', dir, `${base}.test${ext}`),
    path.join(repoPath, '__tests__', dir, `${base}.spec${ext}`),
  ];

  for (const c of candidates) {
    if (fs.existsSync(c)) return { exists: true, path: c };
  }

  // Determine best location: co-located if __tests__ folder exists in dir, else co-located
  const testsDir = path.join(repoPath, dir, '__tests__');
  if (fs.existsSync(testsDir)) {
    return { exists: false, path: path.join(testsDir, `${base}.test${ext}`) };
  }
  return { exists: false, path: path.join(repoPath, dir, `${base}.test${ext}`) };
}

// ── Test template generators ──────────────────────────────────────────────

function generateTestTemplate(sourceFile, sourceContent, framework) {
  const ext = path.extname(sourceFile);
  const base = path.basename(sourceFile, ext);
  const isTS = ext === '.ts' || ext === '.tsx';
  const isComponent = ext === '.tsx' || ext === '.jsx';
  const importPath = `./${base}`;

  // Detect exports from source
  const defaultExportMatch = sourceContent.match(/export\s+default\s+(?:function\s+)?(\w+)|const\s+(\w+)[^=]+=.*=>\s*\(?\s*</);
  const namedExports = [...sourceContent.matchAll(/export\s+(?:const|function|class)\s+(\w+)/g)].map(m => m[1]);
  const hooks = namedExports.filter(n => n.startsWith('use'));
  const components = namedExports.filter(n => /^[A-Z]/.test(n));
  const functions = namedExports.filter(n => /^[a-z]/.test(n) && !n.startsWith('use'));

  const defaultName = defaultExportMatch ? (defaultExportMatch[1] || defaultExportMatch[2] || base) : base;

  if (framework === 'vitest') {
    return generateVitestTemplate(base, importPath, isComponent, isTS, defaultName, hooks, components, functions, sourceContent);
  }
  return generateJestTemplate(base, importPath, isComponent, isTS, defaultName, hooks, components, functions, sourceContent);
}

function generateJestTemplate(base, importPath, isComponent, isTS, defaultName, hooks, components, functions, sourceContent) {
  const lines = [];

  if (isComponent) {
    lines.push(`import React from 'react';`);
    lines.push(`import { render, fireEvent, waitFor } from '@testing-library/react-native';`);
  }

  if (hooks.length > 0) {
    lines.push(`import { renderHook, act } from '@testing-library/react-hooks';`);
  }

  // Import the subject
  const allNamed = [...hooks, ...components, ...functions];
  if (allNamed.length > 0) {
    lines.push(`import ${defaultName}${allNamed.length > 0 ? `, { ${allNamed.join(', ')} }` : ''} from '${importPath}';`);
  } else {
    lines.push(`import ${defaultName} from '${importPath}';`);
  }

  lines.push('');
  lines.push(`// 🤖 Auto-generated by Mobile Team Agent — UnitTestSkill`);
  lines.push(`// Review each test case and fill in the expected values.`);
  lines.push('');

  // Mock common RN modules
  lines.push(`jest.mock('@react-navigation/native', () => ({`);
  lines.push(`  useNavigation: () => ({ navigate: jest.fn(), goBack: jest.fn() }),`);
  lines.push(`  useRoute: () => ({ params: {} }),`);
  lines.push(`}));`);
  lines.push('');

  if (sourceContent.includes('AsyncStorage')) {
    lines.push(`jest.mock('@react-native-async-storage/async-storage', () =>`,);
    lines.push(`  require('@react-native-async-storage/async-storage/jest/async-storage-mock')`);
    lines.push(`);`);
    lines.push('');
  }

  if (sourceContent.includes('axios') || sourceContent.includes('fetch')) {
    lines.push(`jest.mock('axios');`);
    lines.push(`const axios = require('axios');`);
    lines.push('');
  }

  // Component tests
  if (isComponent && defaultName) {
    lines.push(`describe('${defaultName}', () => {`);
    lines.push(`  it('renders without crashing', () => {`);
    lines.push(`    const { toJSON } = render(<${defaultName} />);`);
    lines.push(`    expect(toJSON()).toBeTruthy();`);
    lines.push(`  });`);
    lines.push('');
    lines.push(`  it('matches snapshot', () => {`);
    lines.push(`    const { toJSON } = render(<${defaultName} />);`);
    lines.push(`    expect(toJSON()).toMatchSnapshot();`);
    lines.push(`  });`);

    // Detect onPress handlers
    const pressHandlers = [...sourceContent.matchAll(/testID\s*=\s*['"\`]([^'"\`]+)['"\`]/g)].map(m => m[1]);
    if (pressHandlers.length > 0) {
      lines.push('');
      lines.push(`  // Interaction tests — fill in expected behaviour`);
      for (const id of pressHandlers.slice(0, 3)) {
        lines.push(`  it('handles press on ${id}', () => {`);
        lines.push(`    const { getByTestId } = render(<${defaultName} />);`);
        lines.push(`    fireEvent.press(getByTestId('${id}'));`);
        lines.push(`    // TODO: assert the expected outcome`);
        lines.push(`  });`);
        lines.push('');
      }
    }

    // Detect async operations
    if (sourceContent.includes('async') || sourceContent.includes('await') || sourceContent.includes('.then(')) {
      lines.push(`  it('handles async operations correctly', async () => {`);
      lines.push(`    const { getByTestId } = render(<${defaultName} />);`);
      lines.push(`    await waitFor(() => {`);
      lines.push(`      // TODO: assert that async state updates are reflected in UI`);
      lines.push(`    });`);
      lines.push(`  });`);
      lines.push('');
    }

    lines.push(`});`);
  }

  // Hook tests
  for (const hook of hooks) {
    lines.push('');
    lines.push(`describe('${hook}', () => {`);
    lines.push(`  it('returns expected initial state', () => {`);
    lines.push(`    const { result } = renderHook(() => ${hook}());`);
    lines.push(`    expect(result.current).toBeDefined();`);
    lines.push(`  });`);
    lines.push('');
    lines.push(`  it('updates state correctly', async () => {`);
    lines.push(`    const { result } = renderHook(() => ${hook}());`);
    lines.push(`    await act(async () => {`);
    lines.push(`      // TODO: call a method from result.current and assert state change`);
    lines.push(`    });`);
    lines.push(`  });`);
    lines.push(`});`);
  }

  // Utility/service function tests
  for (const fn of functions.slice(0, 5)) {
    lines.push('');
    lines.push(`describe('${fn}', () => {`);
    lines.push(`  it('returns expected output for valid input', () => {`);
    lines.push(`    // TODO: replace with real input/output`);
    lines.push(`    const result = ${fn}(/* args */);`);
    lines.push(`    expect(result).toBeDefined();`);
    lines.push(`  });`);
    lines.push('');
    lines.push(`  it('handles edge cases gracefully', () => {`);
    lines.push(`    // TODO: test with null, undefined, or empty input`);
    lines.push(`    expect(() => ${fn}(null)).not.toThrow();`);
    lines.push(`  });`);
    lines.push('');
    lines.push(`  it('handles error cases', () => {`);
    lines.push(`    // TODO: assert that errors are thrown or handled correctly`);
    lines.push(`  });`);
    lines.push(`});`);
  }

  return lines.join('\n');
}

function generateVitestTemplate(base, importPath, isComponent, isTS, defaultName, hooks, components, functions, sourceContent) {
  const lines = [];
  lines.push(`import { describe, it, expect, vi, beforeEach } from 'vitest';`);
  if (isComponent) lines.push(`import { render, fireEvent } from '@testing-library/react';`);
  const allNamed = [...hooks, ...components, ...functions];
  if (allNamed.length > 0) {
    lines.push(`import ${defaultName}, { ${allNamed.join(', ')} } from '${importPath}';`);
  } else {
    lines.push(`import ${defaultName} from '${importPath}';`);
  }
  lines.push('');
  lines.push(`// 🤖 Auto-generated by Mobile Team Agent — UnitTestSkill`);
  lines.push('');
  lines.push(`describe('${defaultName}', () => {`);
  lines.push(`  it('works correctly', () => {`);
  lines.push(`    // TODO: fill in test`);
  lines.push(`    expect(true).toBe(true);`);
  lines.push(`  });`);
  lines.push(`});`);
  return lines.join('\n');
}

// ── Coverage parser ───────────────────────────────────────────────────────

function parseCoverageOutput(output) {
  const lines = output.split('\n');
  const results = [];
  let inTable = false;

  for (const line of lines) {
    // Jest coverage table starts with "File" header
    if (line.includes('% Stmts') || line.includes('Statements')) { inTable = true; continue; }
    if (!inTable) continue;
    if (line.includes('---')) continue;
    if (line.trim() === '') { inTable = false; continue; }

    // Parse: File | % Stmts | % Branch | % Funcs | % Lines | Uncovered Line #s
    const match = line.match(/^\s*(.+?)\s*\|\s*([\d.]+)\s*\|\s*([\d.]+)\s*\|\s*([\d.]+)\s*\|\s*([\d.]+)/);
    if (match) {
      const stmts = parseFloat(match[2]);
      results.push({
        file: match[1].trim(),
        statements: stmts,
        branches: parseFloat(match[3]),
        functions: parseFloat(match[4]),
        lines: parseFloat(match[5]),
        status: stmts === 100 ? '✅' : stmts >= 80 ? '🟡' : stmts >= 50 ? '🟠' : '🔴',
      });
    }
  }
  return results;
}

// ── Run tests helper ──────────────────────────────────────────────────────

function runCommand(cmd, args, cwd, timeoutMs = 120000) {
  return new Promise((resolve) => {
    let stdout = '';
    let stderr = '';
    const proc = spawn(cmd, args, { cwd, shell: true });
    proc.stdout.on('data', d => { stdout += d.toString(); });
    proc.stderr.on('data', d => { stderr += d.toString(); });
    const timer = setTimeout(() => { proc.kill(); resolve({ code: -1, stdout, stderr, timedOut: true }); }, timeoutMs);
    proc.on('close', code => { clearTimeout(timer); resolve({ code, stdout, stderr, timedOut: false }); });
  });
}

// ── Skill class ───────────────────────────────────────────────────────────

class UnitTestSkill extends BaseSkill {
  constructor() {
    super();
    this.name = 'UnitTestSkill';
  }

  getTools() {
    return [
      {
        name: 'generate_unit_tests',
        description: 'Generate unit tests for files changed in the current branch vs main. Auto-detects test framework (Jest/Vitest/Mocha), places test files correctly, and immediately runs them. For a project-wide coverage check use check_test_coverage instead.',
        inputSchema: {
          type: 'object',
          properties: {
            target_branch: { type: 'string', description: 'Branch to compare against to find changed files (default: main)' },
            file_path: { type: 'string', description: 'Generate tests for a specific file only (optional — omit to cover all changed files)' },
            framework: { type: 'string', enum: ['jest', 'vitest', 'mocha', 'auto'], description: 'Test framework to use (default: auto-detect from package.json)' },
            run_after_generate: { type: 'boolean', description: 'Run tests immediately after generating (default: true)' },
          },
        },
      },
      {
        name: 'check_test_coverage',
        description: 'Run the full test suite with coverage and report which files are below 100% coverage. Flags files with missing branch, function, statement, or line coverage.',
        inputSchema: {
          type: 'object',
          properties: {
            target_branch: { type: 'string', description: 'Only show coverage for files changed vs this branch (default: shows all)' },
            framework: { type: 'string', enum: ['jest', 'vitest', 'mocha', 'auto'], description: 'Test framework to use (default: auto-detect)' },
            threshold: { type: 'number', description: 'Coverage % below which a file is flagged (default: 100)' },
          },
        },
      },
      {
        name: 'run_tests',
        description: 'Run the project test suite and report results. Pass a file path to run tests for a specific file only.',
        inputSchema: {
          type: 'object',
          properties: {
            file_path: { type: 'string', description: 'Run tests for a specific file or pattern (optional — omit to run all tests)' },
            framework: { type: 'string', enum: ['jest', 'vitest', 'mocha', 'auto'], description: 'Test framework (default: auto-detect)' },
            watch: { type: 'boolean', description: 'Run in watch mode (default: false)' },
          },
        },
      },
    ];
  }

  async handleTool(name, args, context) {
    const { getRepoPath } = context;
    const repoPath = getRepoPath();

    switch (name) {

      case 'generate_unit_tests': {
        const target = args.target_branch || 'main';
        const runAfter = args.run_after_generate !== false;
        const fw = this._resolveFramework(args.framework, repoPath);

        let filesToTest = [];

        if (args.file_path) {
          filesToTest = [args.file_path];
        } else {
          // Get changed files from branch diff
          const changed = await this._getChangedFiles(target, repoPath);
          // Only testable source files — skip test files themselves, JSON, assets
          filesToTest = changed
            .filter(f => /\.(tsx|ts|jsx|js)$/.test(f) && !/\.(test|spec)\.(tsx|ts|jsx|js)$/.test(f))
            .filter(f => !/node_modules|__mocks__|\.d\.ts$/.test(f));
        }

        if (filesToTest.length === 0) {
          return this.textResponse(
            `No testable source files found in changes vs ${target}.\n` +
            `All changed files are either already test files, assets, or config files.`
          );
        }

        let out = `Unit Test Generation\n`;
        out += `${'='.repeat(60)}\n`;
        out += `Framework: ${fw.name} (auto-detected)\n`;
        out += `Files to cover: ${filesToTest.length}\n\n`;

        const generated = [];
        const skipped = [];

        for (const relFile of filesToTest) {
          const fullPath = path.isAbsolute(relFile) ? relFile : path.join(repoPath, relFile);

          if (!fs.existsSync(fullPath)) { skipped.push(`${relFile} (file not found)`); continue; }

          const sourceContent = fs.readFileSync(fullPath, 'utf-8');
          const testFile = findTestFile(relFile, repoPath);

          if (testFile.exists) {
            out += `⏭  ${relFile}\n`;
            out += `   Test file already exists: ${path.relative(repoPath, testFile.path)}\n\n`;
            skipped.push(relFile);
            continue;
          }

          const testContent = generateTestTemplate(relFile, sourceContent, fw.name);

          // Ensure test directory exists
          fs.mkdirSync(path.dirname(testFile.path), { recursive: true });
          fs.writeFileSync(testFile.path, testContent, 'utf-8');

          const testRelPath = path.relative(repoPath, testFile.path);
          out += `✅ Generated: ${testRelPath}\n`;
          out += `   Source:    ${relFile}\n\n`;
          generated.push({ source: relFile, testFile: testRelPath, testPath: testFile.path });
        }

        out += `${'='.repeat(60)}\n`;
        out += `Generated: ${generated.length} test file(s)\n`;
        out += `Skipped:   ${skipped.length} file(s)\n\n`;

        if (generated.length === 0) {
          out += `All changed files already have test files. Run 'check_test_coverage' to see coverage gaps.\n`;
          return this.textResponse(out);
        }

        // Run tests immediately
        if (runAfter) {
          out += `Running generated tests...\n`;
          out += `${'─'.repeat(40)}\n`;

          for (const { testPath, testRelPath } of generated) {
            const result = await runCommand(
              fw.runner,
              [testPath, '--no-coverage', '--passWithNoTests'],
              repoPath
            );

            if (result.timedOut) {
              out += `⏱  ${testRelPath} — TIMED OUT (120s)\n`;
            } else if (result.code === 0) {
              out += `✅ ${testRelPath} — PASSED\n`;
            } else {
              out += `❌ ${testRelPath} — FAILED\n`;
              // Show last 20 lines of error output
              const errLines = (result.stdout + result.stderr).split('\n').filter(l => l.trim()).slice(-20);
              out += errLines.map(l => `   ${l}`).join('\n') + '\n';
              out += `\n   Fix the test file at: ${testRelPath}\n`;
            }
            out += '\n';
          }
        }

        out += `${'='.repeat(60)}\n`;
        out += `Next steps:\n`;
        out += `1. Review each generated test file — fill in TODO sections with real expected values\n`;
        out += `2. Run 'check_test_coverage' to see overall coverage after filling in tests\n`;
        out += `3. Run 'run_tests' anytime to re-verify all tests pass\n`;

        return this.textResponse(out);
      }

      case 'check_test_coverage': {
        const fw = this._resolveFramework(args.framework, repoPath);
        const threshold = args.threshold || 100;
        const targetBranch = args.target_branch || null;

        let out = `Test Coverage Report\n`;
        out += `${'='.repeat(60)}\n`;
        out += `Framework: ${fw.name}\n`;
        out += `Threshold: ${threshold}%\n`;
        if (targetBranch) out += `Scope: changed files vs ${targetBranch}\n`;
        out += `\nRunning coverage... (this may take a moment)\n`;

        const result = await runCommand(fw.coverage, [], repoPath, 180000);

        if (result.timedOut) {
          return this.textResponse(`Coverage run timed out after 3 minutes.\nTry running manually: ${fw.coverage}`);
        }

        const combinedOutput = result.stdout + result.stderr;
        const coverageData = parseCoverageOutput(combinedOutput);

        // Filter to changed files only if target branch specified
        let filteredData = coverageData;
        if (targetBranch && coverageData.length > 0) {
          const changedFiles = await this._getChangedFiles(targetBranch, repoPath);
          const changedBases = changedFiles.map(f => path.basename(f, path.extname(f)).toLowerCase());
          filteredData = coverageData.filter(d =>
            changedBases.some(b => d.file.toLowerCase().includes(b))
          );
        }

        if (filteredData.length === 0 && coverageData.length === 0) {
          out += `\nNo coverage data found. Ensure tests exist and the framework is configured.\n`;
          out += `Raw output:\n${combinedOutput.slice(0, 500)}\n`;
          return this.textResponse(out);
        }

        const below = filteredData.filter(d => d.statements < threshold);
        const passing = filteredData.filter(d => d.statements >= threshold);

        out += `\n${'='.repeat(60)}\n`;
        out += `COVERAGE SUMMARY\n`;
        out += `${'─'.repeat(40)}\n`;
        out += `Total files checked: ${filteredData.length}\n`;
        out += `✅ At/above ${threshold}%: ${passing.length}\n`;
        out += `❌ Below ${threshold}%:   ${below.length}\n\n`;

        if (below.length > 0) {
          out += `FILES NEEDING MORE TESTS\n`;
          out += `${'─'.repeat(40)}\n`;

          // Sort by lowest coverage first
          below.sort((a, b) => a.statements - b.statements);

          for (const d of below) {
            out += `${d.status} ${d.file}\n`;
            out += `   Stmts: ${d.statements}%  |  Branch: ${d.branches}%  |  Funcs: ${d.functions}%  |  Lines: ${d.lines}%\n`;

            if (d.statements < 50) {
              out += `   🔴 CRITICAL: Less than 50% covered — run 'generate_unit_tests' for this file\n`;
            } else if (d.statements < 80) {
              out += `   🟠 LOW: Missing branch/edge case coverage\n`;
            } else {
              out += `   🟡 PARTIAL: Close to full coverage — add a few more edge case tests\n`;
            }
            out += '\n';
          }

          out += `${'='.repeat(60)}\n`;
          out += `To generate missing tests:\n`;
          out += `  "generate unit tests for <filename>"\n`;
          out += `  or: "generate unit tests for all changed files"\n`;
        } else {
          out += `🎉 All files meet the ${threshold}% coverage threshold!\n`;
        }

        return this.textResponse(out);
      }

      case 'run_tests': {
        const fw = this._resolveFramework(args.framework, repoPath);

        let cmd = fw.runner;
        const cmdArgs = [];

        if (args.file_path) {
          const fullPath = path.isAbsolute(args.file_path)
            ? args.file_path
            : path.join(repoPath, args.file_path);
          cmdArgs.push(fullPath);
        }

        if (args.watch) cmdArgs.push('--watch');
        else cmdArgs.push('--passWithNoTests');

        let out = `Running Tests\n`;
        out += `${'='.repeat(60)}\n`;
        out += `Framework: ${fw.name}\n`;
        if (args.file_path) out += `File: ${args.file_path}\n`;
        out += `\n`;

        const result = await runCommand(cmd, cmdArgs, repoPath, 180000);

        if (result.timedOut) {
          return this.textResponse(`${out}Tests timed out after 3 minutes.\nTry running manually: ${cmd} ${cmdArgs.join(' ')}`);
        }

        const combinedOutput = (result.stdout + result.stderr).trim();

        // Extract summary line
        const summaryMatch = combinedOutput.match(/Tests?:.*\d+.*(passed|failed).*/i);
        const suiteMatch = combinedOutput.match(/Test Suites?:.*/i);

        out += result.code === 0 ? `✅ ALL TESTS PASSED\n` : `❌ TESTS FAILED\n`;
        out += `${'─'.repeat(40)}\n`;
        if (suiteMatch) out += `${suiteMatch[0]}\n`;
        if (summaryMatch) out += `${summaryMatch[0]}\n`;
        out += '\n';

        if (result.code !== 0) {
          // Show failures — last 40 lines usually contains the failure detail
          const lines = combinedOutput.split('\n');
          const failStart = lines.findIndex(l => l.includes('FAIL ') || l.includes('● '));
          const failLines = failStart >= 0 ? lines.slice(failStart, failStart + 40) : lines.slice(-40);
          out += `FAILURES:\n${'─'.repeat(40)}\n`;
          out += failLines.join('\n') + '\n\n';
          out += `Fix the failing tests, then run 'run_tests' again.\n`;
        }

        return this.textResponse(out);
      }

      default:
        return null;
    }
  }

  // ── Private helpers ─────────────────────────────────────────────────────

  _resolveFramework(requested, repoPath) {
    if (requested && requested !== 'auto') {
      const map = {
        jest:    { name: 'jest',    runner: 'npx jest', coverage: 'npx jest --coverage --coverageReporters=text' },
        vitest:  { name: 'vitest',  runner: 'npx vitest run', coverage: 'npx vitest run --coverage' },
        mocha:   { name: 'mocha',   runner: 'npx mocha', coverage: 'npx nyc mocha' },
      };
      return map[requested] || detectTestFramework(repoPath);
    }
    return detectTestFramework(repoPath);
  }

  async _getChangedFiles(target, repoPath) {
    try {
      const { stdout } = await execFileAsync('git', [
        '-C', repoPath, 'diff', '--name-only', `${target}...HEAD`,
      ], { maxBuffer: 5 * 1024 * 1024 });
      return stdout.trim().split('\n').filter(Boolean);
    } catch (_) {
      try {
        const { stdout } = await execFileAsync('git', [
          '-C', repoPath, 'diff', '--name-only', `${target}..HEAD`,
        ], { maxBuffer: 5 * 1024 * 1024 });
        return stdout.trim().split('\n').filter(Boolean);
      } catch (_2) {
        return [];
      }
    }
  }

  getPrompt() {
    return this.loadPromptChunk('unit_tests.md') || `### Unit Test Skill
Use 'generate_unit_tests' when a developer asks to generate tests for their changes — auto-detects framework, creates test files, and runs them immediately.
Use 'check_test_coverage' when a developer wants to know their overall coverage gaps.
Use 'run_tests' when a developer wants to run the test suite.
After 'review_branch', always ask: "Would you like me to generate unit tests for your changed files?"`;
  }
}

module.exports = UnitTestSkill;
